version: '3.8'
services:
  express:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express_stocks
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongo/express-stocks
      - JWT_SECRET=somesupersecret
      - NODE_ENV=development
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongo_stocks
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - '27017:27017'

  nginx:
    image: nginx
    container_name: nginx_goals
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express

volumes:
  mongo_data:
